services:
  postgres:
    image: postgres:latest
    container_name: store-postgres-service
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    container_name: store-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${DATA_BASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PWD}
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - my-network

networks:
  my-network:
    external: true

volumes:
  postgres_data:
