services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PWD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
      # ME_CONFIG_BASICAUTH: false
    networks:
      - my-network

  node-auth:
    container_name: node-auth-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - my-network
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PWD=${MAILER_PWD}
    ports:
      - 5050:5050

networks:
  my-network:
    external: true

volumes:
  postgres_data:
